//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronoStick_Input.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChronoStick_Input.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher la fenêtre.
        /// </summary>
        public static string Afficher {
            get {
                return ResourceManager.GetString("Afficher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Délais Ping.
        /// </summary>
        public static string Delais {
            get {
                return ResourceManager.GetString("Delais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simuler un départ :.
        /// </summary>
        public static string Depart {
            get {
                return ResourceManager.GetString("Depart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Départ.
        /// </summary>
        public static string DepartMsg {
            get {
                return ResourceManager.GetString("DepartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à État :.
        /// </summary>
        public static string Etat {
            get {
                return ResourceManager.GetString("Etat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connecté.
        /// </summary>
        public static string EtatMsgCon {
            get {
                return ResourceManager.GetString("EtatMsgCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        public static string EtatMsgErr {
            get {
                return ResourceManager.GetString("EtatMsgErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion de la communication avec le contrôleur de Joystick.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Host UDP Message.
        /// </summary>
        public static string HostUDP {
            get {
                return ResourceManager.GetString("HostUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Masquer la fenêtre.
        /// </summary>
        public static string Masquer {
            get {
                return ResourceManager.GetString("Masquer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chronostick-Input Configuration.
        /// </summary>
        public static string MsgBaloon {
            get {
                return ResourceManager.GetString("MsgBaloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre Patineur (Départ).
        /// </summary>
        public static string NbPatDep {
            get {
                return ResourceManager.GetString("NbPatDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre Sec Min (Départ).
        /// </summary>
        public static string NbSecMinDep {
            get {
                return ResourceManager.GetString("NbSecMinDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre Sec Min (Tour).
        /// </summary>
        public static string NbSecMinTour {
            get {
                return ResourceManager.GetString("NbSecMinTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des Joystick v.
        /// </summary>
        public static string NomLog {
            get {
                return ResourceManager.GetString("NomLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port UDP Message.
        /// </summary>
        public static string PortUDP {
            get {
                return ResourceManager.GetString("PortUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port UDP Config.
        /// </summary>
        public static string PortUDPCfg {
            get {
                return ResourceManager.GetString("PortUDPCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reconnecter.
        /// </summary>
        public static string Reconnecter {
            get {
                return ResourceManager.GetString("Reconnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simuler un tour pour le patineur.
        /// </summary>
        public static string SimulTour {
            get {
                return ResourceManager.GetString("SimulTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double cliquer pour la fenêtre, bouton droit pour le menu.
        /// </summary>
        public static string ToolTipTexte {
            get {
                return ResourceManager.GetString("ToolTipTexte", resourceCulture);
            }
        }
    }
}
